title:              Clean Blog
email:              yeongseon.choe@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Yeongseon Choe
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   yeongseonchoe
github_username:    yeongseon
facebook_username:  yeongseonchoe
linkedin_username:  yeongseonchoe 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
